language: node_js

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.npm/_prebuilds

node_js:
  - "10"

os:
  - linux
  - osx

install:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install snapd && sudo snap install snapcraft --classic; fi

script:
  - npm run build
  - npm run prepare-release
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run package -- linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package -- mac; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package -- win; fi
