theme: jekyll-theme-architect
title: MQTT Explorer
description: Tool to visualize your MQTT topics, a MQTT swiss-army knife
author:
  name: Thomas Nordquist
  picture: https://avatars1.githubusercontent.com/u/7721625?s=460&v=4 
github_username: thomasnordquist
logo: https://user-images.githubusercontent.com/7721625/52227945-5280b580-28b1-11e9-804c-75a842537393.png
plugins:
  - jekyll-seo-tag
google_analytics: UA-133696837-1
