image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node 10

build_script:
  - rm .travis.yml
  - yarn
  - yarn prepare-release
  - yarn package win


test_script:
  - yarn test
