image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

environment:
  TEST_FILES: ExtraBuildTest,BuildTest,extraMetadataTest,filesTest,globTest,nsisUpdaterTest,oneClickInstallerTest,installerTest,appxTest,msiTest,protonTest

install:
  - ps: Install-Product node 10 x64

build_script:
  - set PATH2=%PATH%
#  - set PATH=C:\Windows\System32;C:\Windows;C:\Windows\System32\Wbem;C:\msys64\usr\bin
  - rmdir /s C:\cygwin
  - yarn
  - yarn prepare-release
  - yarn package win


test_script:
  - yarn test
