image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Install-Product node 10

build_script:
  - yarn
  - yarn build
  - yarn prepare-release
  - yarn package appx

test_script:
  - yarn test

artifacts:
  - path: 'build\clean\build\MQTT-Explorer*.appx'

